install:
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/answer.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/btw.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/control.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/files.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/loop.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/notify.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/prompt-editor.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/review.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/session-breakdown.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/split-fork.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/todos.ts
	# Deleted from upstream main branch
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/521cafdb9ed3923e8ace90c5af9d2c7d92c10f86/extensions/context.ts
	curl -O https://raw.githubusercontent.com/HazAT/pi-config/06114f026fb062b8a3aaaca86bad6504e9cc566d/extensions/ghostty.ts
