install:
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/notify.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/answer.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/files.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/review.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/context.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/session-breakdown.ts	
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/prompt-editor.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/loop.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/control.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/pi-extensions/todos.ts
