install:
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/notify.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/answer.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/files.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/review.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/context.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/session-breakdown.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/prompt-editor.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/loop.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/control.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/todos.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/btw.ts
	curl -O https://raw.githubusercontent.com/mitsuhiko/agent-stuff/refs/heads/main/extensions/split-fork.ts
